### ISSUE TITLE
windows10系统 程序无法正常启动

### ISSUE THREAD

**Issue by dengyt2018** [Shinlor/V2RayS#1]
dotnet已经安装有
下面log.txt是错误日志
![dotnet](https://user-images.githubusercontent.com/866095/34864989-c50e26d2-f7b1-11e7-8d4c-435a0ff07ff2.PNG)
[log.txt](https://github.com/Shinlor/V2RayS/files/1625290/log.txt)

**Comment by Bethannfrum** [comment]
Fix and restore to original form and release old documents

**Comment by Shinlor** [comment]
V2Ray配置文件的问题
我在新版里加了新的默认配置文件，代替V2Ray自带的配置文件
同时把V2Ray也带上了
